###############################################
# DATABASE (PRODUCTION)
###############################################
spring.datasource.url=jdbc:mysql://db:3306/lotushrm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

###############################################
# FILE UPLOAD DIR
###############################################
lotusgroup.upload-file.dir=/app/uploads